
version: "3.3"
services:

  dotnetcore:
    build:
      context: ./alternative/findyourasp/Backend
    ports:
      - "8080:8080"
    networks:
      - backend
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  react:
    build:
      context: ./alternative/findyourasp/find-your-language/ClientApp
    ports:
      - "80:80"
    networks:
      - backend
      - frontend
    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  frontend:
  backend:

volumes:
  db-data: